# Generated by Django 2.2 on 2021-06-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shell_app', '0002_ninjas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='dojo',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='shell_app.Dojos'),
        ),
    ]
